#!/bin/bash
set -e

fetch() {
  local VERSION=$1
  if [[ -z $VERSION ]]; then
    echo "Please specify a kernel version."
    exit 1
  fi
  local MAJOR_VERSION=${VERSION:0:1}
  [ -d /usr/src/linux-${VERSION} ] || curl -sSL https://cdn.kernel.org/pub/linux/kernel/v${MAJOR_VERSION}.x/linux-${VERSION}.tar.xz | tar -v -C /usr/src -xJ
}

compile(){
  local VERSION=$1
  local MAJOR_VERSION=${VERSION:0:1}
  local V=( ${VERSION//./ } )
  local MAJOR_MINOR_VERSION="${V[0]}.${V[1]}"

  if [[ -z $VERSION ]]; then
    echo "Please specify a kernel version."
    exit 1
  fi
  if [[ ! -f config/$MAJOR_MINOR_VERSION ]]; then
    echo "$MAJOR_MINOR_VERSION is not supported by default. Please generate your config"
    exit 1
  fi

  cp config/$MAJOR_MINOR_VERSION /usr/src/linux-${VERSION}/.config
  # apply the patches and compile the kernel
  make \
    -C /usr/src/linux-${VERSION} \
    -j $JOBS \
    deb-pkg
}

if [[ $1 = 'fetch' ]]; then
  fetch $2
  exit 0
elif [[ $1 = 'compile' ]]; then
  fetch $2
  compile $2
  exit 0
else
  echo "supported sub-commands are:"
  echo "\tfetch KERNEL_VERSION"
  echo "\tcompile KERNEL_VERSION"
  exit 1
fi
